version: "3"

services:
    nginx:
        image: nginx
        restart: always
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html/
        networks:
            - backend

    php:
        build:
            context: docker/php
        restart: always
        volumes:
            - ./:/var/www/html/
        networks:
            - backend
        depends_on:
            - nginx

    db:
        image: mysql
        restart: always
        volumes:
            - ./docker/db/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${MYSQL_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - 127.0.0.1:${DB_PORT_DOCKER}:3306
        networks:
            - backend

networks:
    backend:
